### ISSUE TITLE
US: Auth [MVP]

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#1]
- Modify the existing ui: https://app.decenterai.com/signup

1. Remove

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/6ce33ee6-b790-4b67-bb40-9786c79fe264)

2. Enable: login should redirect to /signin

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/8e727484-275e-42b4-be11-efef01466fbb)

3. If the user logged in already it should redirect to : 

https://app.decenterai.com/dashboard

User-flow: visiting:  https://app.decenterai.com

1. If user logged in: https://app.decenterai.com/dashboard
2. If user hasn't logged in:  https://app.decenterai.com/signup

Option: Enable Already has account? - `goto 2`

4. Integrate Web3Auth 
      - Get shared email from @VictorKaycee17 
      - Setup the Project 
      - Get the API keys

**Comment by Nasfame** [comment]
Create a new branch from main : feat/auth

**Comment by Abhay-2811** [comment]
confirming the flow: user clicks on "Try demo" -> if signed in -> /dashboard, -> if not signed in -> /signup

Note: no need for different pages i.e signup and login for google auth using web3auth

**Comment by Nasfame** [comment]
> Note: no need for different pages i.e signup and login for google auth using web3auth

Ok
