### ISSUE TITLE
fix: vercel api failure after revamp

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#51]

**Comment by Nasfame** [comment]
Figure out why train is failing

**Comment by Nasfame** [comment]
@techyNonso use logs

1. Login with vercel with shared email

**Comment by techyNonso** [comment]
Made a pr already , the only issue I saw was that for some reason,  web3.storage was not resolved. Have reinstalled it and made a pr

**Comment by Nasfame** [comment]
@techyNonso link the pr with the issue by specifying Resolves or Fixes #<issueNo>

**Comment by Nasfame** [comment]
@techyNonso Blocked: not able to login in

**Comment by Nasfame** [comment]
Investiagtion complete: lighthouse apis are failing cuz env var missing in the vercel deployment

**Comment by Nasfame** [comment]
Resolved
