### ISSUE TITLE
Create CodeOfCoduct

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#55]
https://github.com/DeCenter-AI/app.decenterai.com

![Image](https://github.com/DeCenter-AI/app.decenterai.com/assets/24226219/8e41438a-db36-4d3c-99c3-660ee237b021)

Code of conduct is missing, create one

**Comment by Nasfame** [comment]
https://github.com/prisma/prisma/blob/main/CODE_OF_CONDUCT.md

**Comment by Nasfame** [comment]
@RedValis can u pick this up

**Comment by Nasfame** [comment]
@Abhay-2811 i have reassigned this to @RedValis

**Comment by RedValis** [comment]
Sure, I'll work on it

**Comment by RedValis** [comment]
Code of Conduct added
