### ISSUE TITLE
bugfix: after auth redirect to original route

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#79]
- [x] if user is going to /dashboard/train and user was temorarily redirected to /explore for auth after successfull auth you should redirect to original route that was requested by user . 
- [x] conditional routing [if the route requested by user doesn't exist] it should by default redirect to /dashboard

**Comment by techyNonso** [comment]
We can store the initial route in context or local storage

**Comment by techyNonso** [comment]
What do you think @Abhay-2811

**Comment by Nasfame** [comment]
This issue is resolved atleast after integrating particle network
