### ISSUE TITLE
Learn: Prisma

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/app.decenterai.com#80]
- [x] Watch: https://www.youtube.com/watch?v=RebA5J-rlwg
- [ ] Watch:  https://www.youtube.com/watch?v=D-B77ctsZkY
- [ ]  Do KT(Knowledge Transfer) with @Abhay-2811

**Comment by utkarsh-1602** [comment]
@Abhay-2811 I've created a repo for prisma you call follow
repo link : https://github.com/utkarsh-1602/learn-prisma 

We can connect over lunch call to discuss doubts

**Comment by Nasfame** [comment]
@utkarsh-1602 good job, i am deassigning this issue.

**Comment by Nasfame** [comment]
@Sheriff-Oladimeji @Codebox124 where r u guys at learning prisma?

**Comment by Sheriff-Oladimeji** [comment]
> @Sheriff-Oladimeji @Codebox124 where r u guys at learning prisma?

I have finished the first tutorial. I'll continue with the next tutorial as soon as I finish my current task.
